# Generated by Django 2.2.1 on 2019-05-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='password',
            field=models.IntegerField(default=0),
        ),
    ]
