# Generated by Django 2.2 on 2019-05-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190512_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dropdown',
            field=models.CharField(max_length=10),
        ),
    ]
